"""Global chronological folds, purging, and reproducible manifests."""

from crypto_movement.splits.manifests import (
    BatchManifest,
    BatchManifestRow,
    FoldManifest,
    FoldManifestRow,
    ManifestIntegrityError,
    ManifestProvenance,
    ManifestWrite,
    SplitEndpointInventory,
    build_batch_manifest,
    build_fold_manifest,
    read_batch_manifest_parquet,
    read_fold_manifest_parquet,
    write_batch_manifest_parquet,
    write_fold_manifest_parquet,
)
from crypto_movement.splits.purging import (
    AssignedExample,
    ExampleInterval,
    ExcludedExample,
    ExclusionReason,
    assert_no_partition_duplicates,
    assert_no_target_crossing,
    assign_example_to_fold,
    assign_examples,
)
from crypto_movement.splits.walk_forward import (
    GlobalCutoff,
    GlobalFoldCalendar,
    InnerFoldIdentity,
    LockboxAccessError,
    Partition,
    TimeRange,
    WalkForwardSpec,
    build_global_fold_calendar,
    common_partition_assignments,
)

__all__ = [
    "AssignedExample",
    "BatchManifest",
    "BatchManifestRow",
    "ExampleInterval",
    "ExcludedExample",
    "ExclusionReason",
    "FoldManifest",
    "FoldManifestRow",
    "GlobalCutoff",
    "GlobalFoldCalendar",
    "InnerFoldIdentity",
    "LockboxAccessError",
    "ManifestIntegrityError",
    "ManifestProvenance",
    "ManifestWrite",
    "Partition",
    "SplitEndpointInventory",
    "TimeRange",
    "WalkForwardSpec",
    "assert_no_partition_duplicates",
    "assert_no_target_crossing",
    "assign_example_to_fold",
    "assign_examples",
    "build_batch_manifest",
    "build_fold_manifest",
    "build_global_fold_calendar",
    "common_partition_assignments",
    "read_batch_manifest_parquet",
    "read_fold_manifest_parquet",
    "write_batch_manifest_parquet",
    "write_fold_manifest_parquet",
]
